
package view;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class Principal extends javax.swing.JFrame {

    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelContenedor = new javax.swing.JPanel();
        jPanelContenedorBtn = new javax.swing.JPanel();
        btnValidar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnTotalizar = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        BtnAddInicio = new javax.swing.JButton();
        BtnAddFinal = new javax.swing.JButton();
        txtNro = new javax.swing.JTextField();
        btnAddDespues = new javax.swing.JButton();
        btnDelDespues = new javax.swing.JButton();
        btnObtener = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnVerLista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelContenedor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("datos de entrada")));

        javax.swing.GroupLayout JPanelContenedorLayout = new javax.swing.GroupLayout(JPanelContenedor);
        JPanelContenedor.setLayout(JPanelContenedorLayout);
        JPanelContenedorLayout.setHorizontalGroup(
            JPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JPanelContenedorLayout.setVerticalGroup(
            JPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );

        btnValidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Validar.png"))); // NOI18N
        btnValidar.setText("validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Calcular.png"))); // NOI18N
        btnCalcular.setText("calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Nuevo.png"))); // NOI18N
        btnNuevo.setText("nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnTotalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Total.png"))); // NOI18N
        btnTotalizar.setText("totalizar");
        btnTotalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalizarActionPerformed(evt);
            }
        });

        btnSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Back.png"))); // NOI18N
        btnSalida.setText("salida");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        BtnAddInicio.setText("Add Inicio");

        BtnAddFinal.setText("Add Final");

        btnAddDespues.setText("Add Después");
        btnAddDespues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDespuesActionPerformed(evt);
            }
        });

        btnDelDespues.setText("Del  Después");
        btnDelDespues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelDespuesActionPerformed(evt);
            }
        });

        btnObtener.setText("Obtener");
        btnObtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerActionPerformed(evt);
            }
        });

        jLabel7.setText("Nodo No.");

        btnVerLista.setText("VerLista");

        javax.swing.GroupLayout jPanelContenedorBtnLayout = new javax.swing.GroupLayout(jPanelContenedorBtn);
        jPanelContenedorBtn.setLayout(jPanelContenedorBtnLayout);
        jPanelContenedorBtnLayout.setHorizontalGroup(
            jPanelContenedorBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnValidar)
                .addGap(49, 49, 49)
                .addComponent(BtnAddInicio)
                .addGap(34, 34, 34)
                .addComponent(BtnAddFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addGap(28, 28, 28)
                .addComponent(btnNuevo)
                .addGap(31, 31, 31)
                .addComponent(btnTotalizar)
                .addGap(18, 18, 18)
                .addComponent(btnSalida)
                .addGap(35, 35, 35))
            .addGroup(jPanelContenedorBtnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnVerLista)
                .addGap(79, 79, 79)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtNro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnAddDespues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelDespues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObtener)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContenedorBtnLayout.setVerticalGroup(
            jPanelContenedorBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorBtnLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelContenedorBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValidar)
                    .addComponent(btnCalcular)
                    .addComponent(btnNuevo)
                    .addComponent(btnTotalizar)
                    .addComponent(btnSalida)
                    .addComponent(BtnAddInicio)
                    .addComponent(BtnAddFinal))
                .addGap(23, 23, 23)
                .addGroup(jPanelContenedorBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelContenedorBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelContenedorBtnLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel7))
                        .addComponent(txtNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelContenedorBtnLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(btnAddDespues))
                        .addGroup(jPanelContenedorBtnLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(jPanelContenedorBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnObtener)
                                .addComponent(btnDelDespues))))
                    .addGroup(jPanelContenedorBtnLayout.createSequentialGroup()
                        .addComponent(btnVerLista)
                        .addGap(4, 4, 4)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelContenedorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContenedorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
 
    
    
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
       
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnTotalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTotalizarActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnAddDespuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDespuesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddDespuesActionPerformed

    private void btnDelDespuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelDespuesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelDespuesActionPerformed

    private void btnObtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObtenerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddFinal;
    private javax.swing.JButton BtnAddInicio;
    private javax.swing.JPanel JPanelContenedor;
    private javax.swing.JButton btnAddDespues;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnDelDespues;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnObtener;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton btnTotalizar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JButton btnVerLista;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelContenedorBtn;
    private javax.swing.JTextField txtNro;
    // End of variables declaration//GEN-END:variables

    public JPanel getJPanelContenedor() {
        return JPanelContenedor;
    }

    public void setJPanelContenedor(JPanel JPanelContenedor) {
        this.JPanelContenedor = JPanelContenedor;
    }

    public JButton getBtnCalcular() {
        return btnCalcular;
    }

    public void setBtnCalcular(JButton btnCalcular) {
        this.btnCalcular = btnCalcular;
    }

    public JButton getBtnNuevo() {
        return btnNuevo;
    }

    public void setBtnNuevo(JButton btnNuevo) {
        this.btnNuevo = btnNuevo;
    }

    public JButton getBtnSalida() {
        return btnSalida;
    }

    public void setBtnSalida(JButton btnSalida) {
        this.btnSalida = btnSalida;
    }

    public JButton getBtnTotalizar() {
        return btnTotalizar;
    }

    public void setBtnTotalizar(JButton btnTotalizar) {
        this.btnTotalizar = btnTotalizar;
    }

    public JButton getBtnValidar() {
        return btnValidar;
    }

    public void setBtnValidar(JButton btnValidar) {
        this.btnValidar = btnValidar;
    }

    public JPanel getjPanelContenedorBtn() {
        return jPanelContenedorBtn;
    }

    public void setjPanelContenedorBtn(JPanel jPanelContenedorBtn) {
        this.jPanelContenedorBtn = jPanelContenedorBtn;
    }

    public JButton getBtnAddFinal() {
        return BtnAddFinal;
    }

    public void setBtnAddFinal(JButton BtnAddFinal) {
        this.BtnAddFinal = BtnAddFinal;
    }

    public JButton getBtnAddInicio() {
        return BtnAddInicio;
    }

    public void setBtnAddInicio(JButton BtnAddInicio) {
        this.BtnAddInicio = BtnAddInicio;
    }

    public JButton getBtnAddDespues() {
        return btnAddDespues;
    }

    public void setBtnAddDespues(JButton btnAddDespues) {
        this.btnAddDespues = btnAddDespues;
    }

    public JButton getBtnDelDespues() {
        return btnDelDespues;
    }

    public void setBtnDelDespues(JButton btnDelDespues) {
        this.btnDelDespues = btnDelDespues;
    }

    public JButton getBtnObtener() {
        return btnObtener;
    }

    public void setBtnObtener(JButton btnObtener) {
        this.btnObtener = btnObtener;
    }

    public JTextField getTxtNro() {
        return txtNro;
    }

    public void setTxtNro(JTextField txtNro) {
        this.txtNro = txtNro;
    }

    public JButton getBtnVerLista() {
        return btnVerLista;
    }

    public void setBtnVerLista(JButton btnVerLista) {
        this.btnVerLista = btnVerLista;
    }

    
    

}
