/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author kapac
 */
public class VisLista extends javax.swing.JPanel {

    /**
     * Creates new form VisLista
     */
    public VisLista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblLista = new javax.swing.JTable();
        btnDelInicio = new javax.swing.JButton();
        btnDelFinal = new javax.swing.JButton();
        btnContar = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();

        TblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblLista);

        btnDelInicio.setText("Del Inicio");

        btnDelFinal.setText("Del Final");

        btnContar.setText("Contar  Nodos");

        btnTodos.setText("Mostrar Todos");

        Limpiar.setText("Limpiar");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Lista enlazada libro");

        BtnVolver.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnContar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btnDelInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnTodos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnDelFinal)))
                        .addContainerGap(85, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnVolver)
                            .addComponent(Limpiar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelInicio)
                            .addComponent(btnDelFinal))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnContar)
                            .addComponent(btnTodos))
                        .addGap(32, 32, 32)
                        .addComponent(Limpiar)
                        .addGap(28, 28, 28)
                        .addComponent(BtnVolver)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTable TblLista;
    private javax.swing.JButton btnContar;
    private javax.swing.JButton btnDelFinal;
    private javax.swing.JButton btnDelInicio;
    private javax.swing.JButton btnTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnVolver() {
        return BtnVolver;
    }

    public void setBtnVolver(JButton BtnVolver) {
        this.BtnVolver = BtnVolver;
    }

    public JButton getLimpiar() {
        return Limpiar;
    }

    public void setLimpiar(JButton Limpiar) {
        this.Limpiar = Limpiar;
    }

    public JTable getTblLista() {
        return TblLista;
    }

    public void setTblLista(JTable TblLista) {
        this.TblLista = TblLista;
    }

    public JButton getBtnContar() {
        return btnContar;
    }

    public void setBtnContar(JButton btnContar) {
        this.btnContar = btnContar;
    }

    public JButton getBtnDelFinal() {
        return btnDelFinal;
    }

    public void setBtnDelFinal(JButton btnDelFinal) {
        this.btnDelFinal = btnDelFinal;
    }

    public JButton getBtnDelInicio() {
        return btnDelInicio;
    }

    public void setBtnDelInicio(JButton btnDelInicio) {
        this.btnDelInicio = btnDelInicio;
    }

    public JButton getBtnTodos() {
        return btnTodos;
    }

    public void setBtnTodos(JButton btnTodos) {
        this.btnTodos = btnTodos;
    }

    

}
