/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author estra
 */
public class VistaLista extends javax.swing.JPanel {

    /**
     * Creates new form VistaLista
     */
    public VistaLista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelInicio = new javax.swing.JButton();
        btnDelFinal = new javax.swing.JButton();
        btnContar = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblLista = new javax.swing.JTable();

        btnDelInicio.setText("Del Inicio");

        btnDelFinal.setText("Del Final");

        btnContar.setText("Contar  Nodos");

        btnTodos.setText("Mostrar Todos");

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Lista enlazada ");

        BtnVolver.setText("Volver");

        TblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnDelInicio)
                .addGap(34, 34, 34)
                .addComponent(btnDelFinal)
                .addGap(47, 47, 47)
                .addComponent(btnTodos)
                .addGap(29, 29, 29)
                .addComponent(btnContar)
                .addGap(28, 28, 28)
                .addComponent(Limpiar)
                .addGap(34, 34, 34)
                .addComponent(BtnVolver)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelInicio)
                    .addComponent(btnDelFinal)
                    .addComponent(btnTodos)
                    .addComponent(btnContar)
                    .addComponent(Limpiar)
                    .addComponent(BtnVolver))
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTable TblLista;
    private javax.swing.JButton btnContar;
    private javax.swing.JButton btnDelFinal;
    private javax.swing.JButton btnDelInicio;
    private javax.swing.JButton btnTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnVolver() {
        return BtnVolver;
    }

    public void setBtnVolver(JButton BtnVolver) {
        this.BtnVolver = BtnVolver;
    }

    public JButton getLimpiar() {
        return Limpiar;
    }

    public void setLimpiar(JButton Limpiar) {
        this.Limpiar = Limpiar;
    }

    public JTable getTblLista() {
        return TblLista;
    }

    public void setTblLista(JTable TblLista) {
        this.TblLista = TblLista;
    }

    public JButton getBtnContar() {
        return btnContar;
    }

    public void setBtnContar(JButton btnContar) {
        this.btnContar = btnContar;
    }

    public JButton getBtnDelFinal() {
        return btnDelFinal;
    }

    public void setBtnDelFinal(JButton btnDelFinal) {
        this.btnDelFinal = btnDelFinal;
    }

    public JButton getBtnDelInicio() {
        return btnDelInicio;
    }

    public void setBtnDelInicio(JButton btnDelInicio) {
        this.btnDelInicio = btnDelInicio;
    }

    public JButton getBtnTodos() {
        return btnTodos;
    }

    public void setBtnTodos(JButton btnTodos) {
        this.btnTodos = btnTodos;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

   

}
