/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author estra
 */
public class Entrada extends javax.swing.JPanel implements Vista {

    /**
     * Creates new form Entrada
     */
    public Entrada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Implementación de Vista (salida por consola)
    @Override
    public void showHeader(int size) {
        System.out.println("==== BUSQUEDA DE MAXIMO EN VECTOR (" + size + " elementos) ====");
    }

    @Override
    public void showMemoryAdvice() {
        System.out.println("Nota: Para 500M ints se requieren ~2GB de heap. Ejecuta con -Xms4g -Xmx6g si es posible.");
    }

    @Override
    public void showInfo(String msg) {
        System.out.println("[INFO] " + msg);
    }

    @Override
    public void showResult(String label, int max, long ms) {
        System.out.println(String.format("[RESULT] %s -> max=%d tiempo=%d ms", label, max, ms));
    }

    @Override
    public void showWarning(String msg) {
        System.out.println("[WARN] " + msg);
    }
}
